create table "public"."books" (
    "id" bigint generated by default as identity not null,
    "gutenberg_id" bigint not null,
    "metadata" jsonb default '{}'::jsonb,
    "content" text,
    "created_at" timestamp with time zone not null default now(),
    "text_analysis" jsonb default '{}'::jsonb
);


alter table "public"."books" enable row level security;

CREATE UNIQUE INDEX books_gutenberg_id_unique_idx ON public.books USING btree (gutenberg_id);

CREATE UNIQUE INDEX books_pkey ON public.books USING btree (id);

alter table "public"."books" add constraint "books_pkey" PRIMARY KEY using index "books_pkey";

grant delete on table "public"."books" to "anon";

grant insert on table "public"."books" to "anon";

grant references on table "public"."books" to "anon";

grant select on table "public"."books" to "anon";

grant trigger on table "public"."books" to "anon";

grant truncate on table "public"."books" to "anon";

grant update on table "public"."books" to "anon";

grant delete on table "public"."books" to "authenticated";

grant insert on table "public"."books" to "authenticated";

grant references on table "public"."books" to "authenticated";

grant select on table "public"."books" to "authenticated";

grant trigger on table "public"."books" to "authenticated";

grant truncate on table "public"."books" to "authenticated";

grant update on table "public"."books" to "authenticated";

grant delete on table "public"."books" to "service_role";

grant insert on table "public"."books" to "service_role";

grant references on table "public"."books" to "service_role";

grant select on table "public"."books" to "service_role";

grant trigger on table "public"."books" to "service_role";

grant truncate on table "public"."books" to "service_role";

grant update on table "public"."books" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."books"
as permissive
for insert
to anon
with check (true);


create policy "Enable read access for all users"
on "public"."books"
as permissive
for select
to public
using (true);

