create table "public"."books" (
    "id" bigint generated by default as identity not null,
    "gutenberg_id" bigint not null,
    "metadata" jsonb default '{}'::jsonb,
    "content" text,
    "created_at" timestamp with time zone not null default now(),
    "text_analysis" jsonb default '{}'::jsonb
);


alter table "public"."books" enable row level security;

CREATE UNIQUE INDEX books_gutenberg_id_unique_idx ON public.books USING btree (gutenberg_id);

CREATE UNIQUE INDEX books_pkey ON public.books USING btree (id);

alter table "public"."books" add constraint "books_pkey" PRIMARY KEY using index "books_pkey";

grant delete on table "public"."books" to "anon";

grant insert on table "public"."books" to "anon";

grant references on table "public"."books" to "anon";

grant select on table "public"."books" to "anon";

grant trigger on table "public"."books" to "anon";

grant truncate on table "public"."books" to "anon";

grant update on table "public"."books" to "anon";

grant delete on table "public"."books" to "authenticated";

grant insert on table "public"."books" to "authenticated";

grant references on table "public"."books" to "authenticated";

grant select on table "public"."books" to "authenticated";

grant trigger on table "public"."books" to "authenticated";

grant truncate on table "public"."books" to "authenticated";

grant update on table "public"."books" to "authenticated";

grant delete on table "public"."books" to "service_role";

grant insert on table "public"."books" to "service_role";

grant references on table "public"."books" to "service_role";

grant select on table "public"."books" to "service_role";

grant trigger on table "public"."books" to "service_role";

grant truncate on table "public"."books" to "service_role";

grant update on table "public"."books" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."books"
as permissive
for insert
to anon
with check (true);


create policy "Enable read access for all users"
on "public"."books"
as permissive
for select
to public
using (true);


CREATE TRIGGER fetch_book_content AFTER INSERT ON public.books FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://kxfbzqwdkpcskvaahiyj.supabase.co/functions/v1/fetch_book_content', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmJ6cXdka3Bjc2t2YWFoaXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxODkzNDAsImV4cCI6MjA1Mzc2NTM0MH0.Tb5XmV4EiR_jOIyrDUrJvkOlFs58O9lk6QdrTwIkk_A"}', '{}', '5000');

CREATE TRIGGER text_analysis AFTER INSERT ON public.books FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://kxfbzqwdkpcskvaahiyj.supabase.co/functions/v1/text_analysis', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmJ6cXdka3Bjc2t2YWFoaXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxODkzNDAsImV4cCI6MjA1Mzc2NTM0MH0.Tb5XmV4EiR_jOIyrDUrJvkOlFs58O9lk6QdrTwIkk_A"}', '{}', '5000');


